version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s [%(module)s:%(lineno)s]%(levelname)s--%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  custom:
    (): utils.logging_util.SensitiveDataFormatter
    format: "%(asctime)s [%(module)s:%(lineno)s]%(levelname)s--%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: custom
    stream: ext://sys.stdout
  file_handler:
    (): utils.logging_util.CustomRotatingFileHandler
    level: DEBUG
    formatter: custom
    filename: model_oversight_dev_{date}.log
    file_path: /Users/krzysiekbienias/Documents/GitHub/Portfolio_Theorem/HelperFiles
    max_bytes: 10485760 #10MB
    backup_count: 20
    encoding: utf8

loggers:
  sampleLogger:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file_handler]
